version: "3"

services:
  #MongoDB container
  mongo_db:
    container_name: articlesDatabase
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db
  #articles_api container
  articles_api:
    build: .
    ports:
      - 4000:4000
    environment:
      APP_NAME: articles_api
      PORT: 4000
      DB_URI: mongodb://mongo_db:27017/articles_api
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}