version: '3'

services:
  node:
    image: node:latest
    volumes:
      - "./api:/var/www"  
    ports:
      - "8080:3000"
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

