# IMPORTE IMAGE NODE POUR EXECUTER LE CONTENEUR QUI EXECUTE NODE A PARTIR DE DOCKER HUB
FROM node:alpine 

# EMPLACEMENT DANS LE CONTENEUR OU L'APPLICATION NODE SERA COPIÉE & EXECUTÉE
WORKDIR /usr/src/app

# COPIE LE PACKAGE.JSON
COPY ./package.json ./

# COPIE LE PACKAGE-LOCK.JSON
COPY ./package-lock.json ./

# INSTALLE LES DEPENDANCES DE L'APPLICATION EN UTILISANT PACKAGE.JSON & PACKAGE-LOCK.JSON
RUN npm install

# CREER UNE COPIE DU DOSSIER SRC EN LOCAL DANS LE CONTENEUR
COPY ./src ./src

# CREER UNE COPIE DU .ENV EN LOCAL DANS LE CONTENEUR
COPY ./.env ./

# CREER UNE COPIE DU .CONFIG EN LOCAL DANS LE CONTENEUR
COPY ./config.js ./

# EXECUTE CES COMMANDES POUR INSTALLER LES DÉPENDANCES ET EXECUTER L'APPLICATION DU CONTENEUR
CMD ["npm", "start"]